Feed Frontend
WebDesign3-DHBW/Trail-App pull request #14
Opened 2020-12-28 12:57 UTC by NataschaForster

Styling is done according to our Layout in Figma

2020-12-28 18:22 UTC, eisenils requested changes
Ohne die Claps sieht es für mich alles gerade sehr stark linksgerichtet aus. Vielleicht ist das aber auch nur mein persönlicher Eindruck. Vielleicht kann das Datum (oder etwas anderes) ja nach rechts, sodass es nicht ganz so leer wirkt.
Ansonsten gefällt mir das schon gut, auch wenn ich nochmal mit etwas `spacing` zwischen den einzelnen `containern` spielen würde 😃

2020-12-28 18:22 UTC, eisenils commented on src/components/Feed.jsx
> +        <FeedActivity></FeedActivity>
```suggestion
        <FeedActivity />
```

2020-12-28 18:22 UTC, eisenils commented on src/components/FeedActivity.jsx
> +          <p className={classes.name}><strong>Name</strong> <br/> x Stationen, x Übungen </p>
Das wäre besser, wenn wir das in eine `Typography `Komponente umwandeln, dann ist es nicht so klein 🤔

2020-12-28 18:22 UTC, eisenils commented on src/components/FeedActivity.jsx
> +                </Typography>
Das muss noch anders gelöst werden, da sonst die Übungen immer anders floaten. Sieht man jetzt schon den Unterschied zwischen einer dünnen 1 und einer dickeren 2

2020-12-28 18:45 UTC, felixkeller98 requested changes
Echt super gemacht @NataschaForster!🥰
Ich habe nur noch ein paar Stellen gefunden, wo wir Code herausschmeißen können und habe noch kleinere Design-Änderungen vogeschlagen.

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginBottom: theme.spacing(1),
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +  },
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginTop: theme.spacing(0),
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginLeft: theme.spacing(3),
```suggestion
    marginLeft: theme.spacing(2),
```
Dann ist das Datum auf einer Linie mit dem anderen Content.

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginTop: theme.spacing(1)
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginBottom: theme.spacing(0),
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +      left: theme.spacing(2)
```suggestion
      margin: theme.spacing(2, 0),
```
Damit sind mehrere dieser Activity-Cards schön ausseinander.

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    display: "flex",
```suggestion
    display: "flex",
    margin: theme.spacing(0, 2, 1),
```
Das löst einige Probleme mit Margins, an stellen wo man es jetzt nicht mehr braucht. :)

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginLeft: theme.spacing(2)
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginTop: theme.spacing(1)
```suggestion
```

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +    marginRight: theme.spacing(2)
```suggestion
    marginRight: theme.spacing(1),
    color: theme.palette.primary.main,
    fontWeight: theme.typography.fontWeightBold,
```
Hier könnte man noch wie in Figma die Zahl dick und blau machen.

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +          <p className={classes.name}><strong>Name</strong> <br/> x Stationen, x Übungen </p>
```suggestion
          <div className={classes.header}>
            <div className={classes.name}>Name</div>
            <Typography variant="subtitle2">x Stationen, x Übungen</Typography>
          </div>
```
Diese p-Tags machen einige Probleme, weil die von sich aus schon Margins mitbringen^^
Ich würde hier das Header-Div reinmachen das ich angesprochen hatte, damit wir Avatar und Text zentrieren können.
Die p-Tags habe ich durch ein gestylten Div + ein subtitle2 ersetzt. Das passt ganz gut denke ich.

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +                    <span className={classes.duration}>5,4 Min</span>
```suggestion
                    <span className={classes.duration}> 5,4 Min</span>
```
Mit dem Abstand haben wir ein Margin weniger :D

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +                </Typography>
```suggestion
```
Das könnte schon Mal raus, weil die doppelten Elemente dann aus der Datenbank kommen.

2020-12-28 18:45 UTC, felixkeller98 commented on src/components/TitleBar.jsx
> +    marginLeft: theme.spacing(2)
```suggestion
```
Mit den jetzigen Änderungen wäre jetzt wieder alles auf einer Fluchtlinie.

2020-12-28 18:46 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +          <p className={classes.name}><strong>Name</strong> <br/> x Stationen, x Übungen </p>
Hab's in meinem Review umgewandelt. Dann hätten wir es so wie in Figma. Kannst ja Mal was du davon hältst. 🙂

2020-12-28 18:50 UTC, felixkeller98 commented on src/components/FeedActivity.jsx
> +                </Typography>
Hm das könnte man vielleicht verhindern, wenn wir dem span ein inline-block und eine feste Breite geben :)

2021-01-04 15:51 UTC, felixkeller98 approved these changes

2021-01-08 09:55 UTC, merged